### ISSUE TITLE
Export Datei wird nicht erstellt

### ISSUE THREAD

**Issue by DonLars** [pdir/content-migration-bundle#1]
Nach der Installation konnte ich zwar den Export Button in der Seitenstruktur nutzen. Es wurde auch ein Unterordner erstellt, jedoch keine Datei, die ich auf einer anderen Seite wieder importieren könnte. 

 ![Bildschirmfoto 2022-03-29 um 15 22 59](https://user-images.githubusercontent.com/1670167/160621036-aed689f4-66d7-4c7f-ad59-dc634210012b.jpg)

**Comment by MDevster** [comment]
@Carino Wir haben Version 1.0.0 veröffentlicht, jetzt sollte es gehen!
