### ISSUE TITLE
Error with export

### ISSUE THREAD

**Issue by sdahlmann** [pdir/content-migration-bundle#3]
By the export function become the error: "Pdir\ContentMigrationBundle\Controller\PageExportController::withLeadingZeroes(): Argument #1 ($number) must be of type string, int given, called in /var/www/vhosts/h15621.web113.dogado.net/httpdocs/sdw-cms2/vendor/pdir/content-migration-bundle/src/Controller/PageExportController.php on line 118".
I use Contao 4.13.15 and PHP 8.1.9 with Dogado SSD Hosting or on lokal MAC I use PHP 8.2.x with MAMP PRO.
When I use PHP 8.0.22 then I haven‘t the error.
Can you fix this please, for PHP 8.1.x and PHP 8.2.x?
Many thanks.

**Comment by seibtph** [comment]
Fixed in version 1.0.1
